

---
kind: Service
apiVersion: v1
metadata:
  name: keycloak-service
spec:
  type: LoadBalancer
  selector:
    app: keycloak-service
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  KEYCLOAK_ADMIN: 'admin'

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW5AMTIz

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  selector:
      matchLabels:
        app: keycloak-service
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-service
    spec:
      containers:
       - name: keycloak-service
         image: us-central1-docker.pkg.dev/nagp-amcart/amcart-repo/keycloak:latest
         ports:
         - containerPort: 8080
         args: ["start-dev"]
         envFrom:
            - configMapRef:
                name: keycloak-config
            - secretRef:
                name: keycloak-secret